#!/bin/sh
#
# Run tests under Python 3

set -eux

for X in $(py3versions --supported)
do
	${X} -m pytest -W always -k 'not redismod and onlynoncluster and not module and not busy_loading_disconnects_socket and not busy_loading_from_pipeline_immediate_command and not busy_loading_from_pipeline'
done
